### ISSUE TITLE
The module config section does not get added to the admin

### ISSUE THREAD

**Issue by marius-bica** [godvsdeity/simplecoding-mail#1]
After installing the module via composer, there is no "Simplecoding" section for configuring it in the backend.

Steps to reproduce:
1. install the module via composer
2. clear the cache 
3. login to admin and go to Stores -> Configuration. There is no "SIMPLECODING" section there

Magento 2 version: Magento 2.0.6

**Comment by apasare** [comment]
this might be silly to ask, but is the module enabled: 
`php bin/magento module:status` what does it say?
