### ISSUE TITLE
Implement getMessage method for compatibility with magento 2.2

### ISSUE THREAD

**Issue by marius-bica** [godvsdeity/simplecoding-mail#2]
The `SimpleCoding\Mail\Transport\Smtp` class implements the `Magento\Framework\Mail\TransportInterface` interface which got a new method in the 2.2 version, `getMessage`. From my tests, that is all that's required to be compatible with magento 2.2

**Comment by apasare** [comment]
Just made a new release with this fix + some refactoring on config logic: [v1.0.0](https://github.com/godvsdeity/simplecoding-mail/releases/tag/v1.0.0)
